function _update_ps1() {
    PS1="$($HOME/.bin/powerline-go -error $? -jobs $(jobs -p | wc -l) -modules venv,user,host,cwd,perms,git,jobs,root -colorize-hostname -hostname-only-if-ssh -cwd-mode semifancy -cwd-max-depth 3 -path-aliases \~/git=λ -git-mode simple -ignore-repos ~ -theme ~/.config/powerline-go/config.json)"

    # Uncomment the following line to automatically clear errors after showing
    # them once. This not only clears the error for powerline-go, but also for
    # everything else you run in that shell. Don't enable this if you're not
    # sure this is what you want.

    #set "?"
}

if [ "$TERM" != "linux" ] && [ -f "$HOME/.bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
