export FZF_DEFAULT_OPTS='--height=~20 --layout=reverse --info=inline -0 -1 --no-mouse --scroll-off=1 --color=16'
export FZF_COMPLETION_TRIGGER='*'

source ~/.config/fzf/completion.bash
source ~/.config/fzf/key-bindings.bash
